language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
  - mysql
#addons: # get google-chrome-stable
#  chrome: stable

#install:
#    - wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
#    - unzip ~/chromedriver_linux64.zip -d ~/
#    - rm ~/chromedriver_linux64.zip
#    - sudo mv -f ~/chromedriver /usr/local/share/
#    - sudo chmod +x /usr/local/share/chromedriver

before_install:
  - nvm install --lts
  - gem install rake
before_script:
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('ICTPass1') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - bundle install --gemfile=Gemfile
  - bundle exec rake db:create
  - bundle exec rake db:migrate

  - yarn
script:
  - bundle exec rake test
  #- bundle exec rake test:system
